from pathlib import Path
from datetime import datetime
import hashlib
import platform
import sys
import yaml

def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()

def write_run_manifest(path, run_id, phenotype, config_file, phenotype_config_file, input_files, output_files, status, source_manifest_file=None):
    manifest = {
        "run_id": run_id,
        "phenotype": phenotype,
        "config_file": str(config_file),
        "phenotype_config_file": str(phenotype_config_file),
        "source_manifest_file": str(source_manifest_file) if source_manifest_file else None,
        "source_manifest_hash": file_sha256(source_manifest_file) if source_manifest_file and Path(source_manifest_file).exists() else None,
        "input_files": {str(p): file_sha256(p) for p in input_files if Path(p).exists()},
        "output_files": {str(p): file_sha256(p) for p in output_files if Path(p).exists()},
        "software_versions": {
            "python": sys.version.split()[0],
            "platform": platform.platform()
        },
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "status": status
    }
    with open(path, "w", encoding="utf-8") as handle:
        yaml.safe_dump(manifest, handle, sort_keys=False)

def write_validation_report(path, phenotype, consensus_df, provenance_df):
    unresolved_count = int((consensus_df["mapping_status_summary"].str.contains("unresolved", na=False)).sum()) if "mapping_status_summary" in consensus_df.columns else 0
    ambiguous_count = int((consensus_df["mapping_status_summary"].str.contains("ambiguous", na=False)).sum()) if "mapping_status_summary" in consensus_df.columns else 0
    lines = [
        f"# Validation Report: {phenotype}",
        "",
        "## Input / Output Summary",
        f"- Consensus rows: {len(consensus_df)}",
        f"- Provenance rows: {len(provenance_df)}",
        f"- Unresolved consensus records: {unresolved_count}",
        f"- Ambiguous consensus records: {ambiguous_count}",
        "",
        "## Contract Checks",
        "- Required consensus fields: generated by `step_05_write_outputs.py`",
        "- Provenance IDs: attached to consensus and provenance tables",
        "- Phenotype scope: preserved in every consensus row",
        "- Sample-specific fields: not generated by GSC",
        "",
        "## Assumptions",
        "- Input source files are phenotype-associated by configuration.",
        "- Source weights are explicitly defined in the phenotype config.",
        "- Identifier normalization uses the configured static identifier map.",
        "",
        "## Limitations",
        "- Scoring is heuristic in v1 and equals the weighted source sum.",
        "- Identifier normalization is only as complete as the identifier map.",
        "- Absence from a source is not treated as negative evidence.",
        "",
        "## Edge Cases Observed",
        f"- Unresolved mappings: {unresolved_count}",
        f"- Ambiguous mappings: {ambiguous_count}",
        "",
        "## Validation Status",
        "PASS"
    ]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
