import json
from pathlib import Path
from typing import Any, Dict

from gene_set_consensus.tep.envelope import build_envelope
from gene_set_consensus.tep.manifest import build_manifest
from gene_set_consensus.tep.payload import build_payload
from gene_set_consensus.tep.run_context import load_finalized_run_context


def build_gsc_tep(
    final_run_manifest_path: str | Path,
    validation_state: str = "candidate",
) -> Dict[str, Any]:
    """Build a complete GSC-TEP object.

    Parameters
    ----------
    final_run_manifest_path:
        Path to finalized run manifest generated by
        Step 07 finalization.
    validation_state:
        Current validation state for the generated TEP.

    Returns
    -------
    dict
        JSON-serializable GSC-TEP object with envelope, manifest, and payload.
    """

    run_context = load_finalized_run_context(
        final_run_manifest_path
    )

    manifest = build_manifest(
        run_context=run_context,
    )

    envelope = build_envelope(
        run_context=run_context,
        validation_state=validation_state,
    )

    payload = build_payload(
        release_id=run_context["release_id"],
        manifest=manifest,
    )

    return {
        "envelope": envelope,
        "manifest": manifest,
        "payload": payload,
    }


def default_output_path(
    run_context: Dict[str, Any],
) -> Path:
    """Return the default output path for a GSC-TEP JSON file."""
    return (
        Path("results")
        / "teps"
        / "gsc"
        / run_context["package_id"]
        / "gsc_tep.json"
    )


def authoritative_output_path(
    run_context: Dict[str, Any],
) -> Path:
    """Return authoritative run-scoped TEP path."""
    return (
        Path("results")
        / "teps"
        / "gsc"
        / run_context["package_id"]
        / run_context["run_id"]
        / "gsc_tep.json"
    )


def convenience_output_path(
    run_context: Dict[str, Any],
) -> Path:
    """Return package-level convenience TEP path."""
    return (
        Path("results")
        / "teps"
        / "gsc"
        / run_context["package_id"]
        / "gsc_tep.json"
    )



def write_gsc_tep(
    tep: Dict[str, Any],
    output_path: str | Path,
) -> Path:
    """Write a GSC-TEP object to JSON."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as handle:
        json.dump(
            tep,
            handle,
            indent=2,
            sort_keys=True,
        )
        handle.write("\n")

    return path


def build_and_write_gsc_tep(
    final_run_manifest_path: str | Path,
    output_path: str | Path | None = None,
    validation_state: str = "candidate",
) -> Path:
    """Build and write a GSC-TEP JSON file."""

    run_context = load_finalized_run_context(
        final_run_manifest_path
    )

    tep = build_gsc_tep(
        final_run_manifest_path=final_run_manifest_path,
        validation_state=validation_state,
    )

    authoritative_path = authoritative_output_path(
        run_context=run_context
    )

    write_gsc_tep(
        tep=tep,
        output_path=authoritative_path,
    )

    mirror_path = convenience_output_path(
        run_context=run_context
    )

    write_gsc_tep(
        tep=tep,
        output_path=mirror_path,
    )

    return authoritative_path